# Generated by Django 5.0.3 on 2024-03-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField()),
                ('retailer', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
    ]
