# Generated by Django 5.0.3 on 2024-03-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alter_name', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100, null=True)),
                ('created_time', models.DateTimeField()),
                ('retailer', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=100, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('old_price', models.FloatField(null=True)),
                ('unit', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
