# Generated by Django 5.0.3 on 2024-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonproductname',
            name='id',
        ),
        migrations.AlterField(
            model_name='commonproductname',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='commonproductname',
            index=models.Index(fields=['name'], name='products_co_name_f689a6_idx'),
        ),
    ]
